export {default as MyDrive } from './MyDrive/index';
export {default as Shared } from './Shared/index';
export {default as Recent } from './Recent/index';
export {default as Trash } from './Trash/index';
export {default as SignUp } from './SignUp/index';
export {default as SignIn } from './SignIn/index';
export {default as OrganizationDash} from './OrganizationDash/index';
export {default as InstituteDash} from './InstituteDash/index';
export {default as StudentDash} from './StudentDash/index';
export {default as TeacherDash} from './TeacherDash/index';
export {default as InboxMail} from './Inbox/index';
export {default as DraftMail} from './Drafts/index';
export {default as SentMail} from './Sent/index';
export {default as OrganizationSignUp} from './OrganizationSignUp/index';
export {default as OrganizationLogin} from './OrganizationLogin/index';
export {default as AddInstitute} from './AddInstitute/index';
export {default as InstituteLogin} from './InstituteLogin/index';
export {default as InstiAddStaff} from './InstiAddStaff/index';
export {default as OrgAddStaff} from './OrgAddStaff/index';
export {default as AddStudent} from './AddStudent/index';
export {default as AddTeacher} from './AddTeacher/index';
export {default as StaffLogin} from './StaffLogin/index';
export {default as TeacherLogin} from './TeacherLogin/index';
export {default as StudentLogin} from './StudentLogin/index';
export {default as PasswordChange} from './PasswordChange/index'; 
export {default as InstiList} from './InstiList/index';
export {default as InstiStaffList} from './InstiStaffList/index';
export {default as OrgStaffList} from './OrgStaffList/index';
export {default as TeacherList} from './TeacherList/index';
export {default as StudentList} from './StudentList/index';
export {default as ViewFolder} from './ViewFolder/index';